pipeline {
    agent any

    tools {
        nodejs "node18"
    }

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'github-creds',
                    url: 'https://github.com/adithyasai28/student-mgmt-backend.git',
                    branch: 'main'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'npm test'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                    docker build -t student-mgmt-backend:jenkins .
                '''
            }
        }
    }

    post {
        success {
            echo "Build Successful 🎉"
        }
        failure {
            echo "Build Failed ❌"
        }
    }
}
